# exit-idle-time is enabled by default in upstream, because it makes
# console logins work nicely (the daemon is not left around forever
# after logout). Graphical sessions are expected to somehow disable
# the automatic shutdown for the duration of the session, but at least
# Nemo doesn't currently do that, and since console logins are not
# that important, we can disable the automatic shutdown here. With
# systemd user sessions it should be possible to handle this properly,
# so this change should be eventually dropped.
exit-idle-time = -1

# Modern devices are fast enough to up the resampler quality a bit.
# In really low-end devices it still might make sense to have speex-fixed-2.
resample-method = speex-fixed-4

# Enable flat volumes
flat-volumes = yes
